version: "3.8"

services:
  dev-env:
    build: .
    container_name: dev-env
    volumes:
      - ~/.ssh:/root/.ssh
      - ../Projects:/root/Projects
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
